version: v0.10.0-alpha.0

log:
    level: debug

serve:
    read:
        host: 0.0.0.0
        port: 4466
    write:
        host: 0.0.0.0
        port: 4467

namespaces:
    - id: 1
      name: groups

dsn: memory
